### ISSUE TITLE
Plain-text trace output for integration with log aggregators

### ISSUE THREAD

**Issue by ltmon** [jitlogic/zorka#159]
A plain text output for the tracer would very useful, as this would allow easy integration with centralized log aggregators (Splunk/SumoLogic/LogStash/etc. etc.) for APM or audit purposes. The existing formats (fressian and zabbix) are much more difficult to work with in these systems.

I've made a rough start, but am a long way from a pull request -- and would need some help understanding the TraceRecord structure to get a proper version, but the format I've used is below. 

This is just an idea of what would be most easy for these types of systems, which generally work best with any basic key/value structure.

```
[Sun Mar 15 18:14:51 EST 2015] class=com.mysql.jdbc.PreparedStatement, method=executeQuery, SQL="select this_.USER_ID as USER_ID1_0_0_, this_.USERNAME as USERNAME2_0_0_, this_.PASSWORD as PASSWORD3_0_0_, this_.EMAIL as EMAIL4_0_0_ from USERS this_, DB=testdb", time=2004633
[Sun Mar 15 18:14:51 EST 2015] class=com.mysql.jdbc.StatementImpl, method=executeQuery, SQL="SHOW WARNINGS", DB=testdb, time=1149703
[Sun Mar 15 18:14:51 EST 2015] class=org.apache.catalina.core.StandardEngineValve, method=invoke, URI=/TestApp/, STATUS=200, CookieIn__JSESSIONID=B688A700826A68B4A75681B1BD4230AC, CookieIn__session_id_8000=0422fca3e7b35d4462851080012858df39ff7666, CookieIn__splunkweb_csrf_token_8000=15573489094520950050, HdrIn__host=localhost:8080, HdrIn__cookie=JSESSIONID=B688A700826A68B4A75681B1BD4230AC; session_id_8000=0422fca3e7b35d4462851080012858df39ff7666; splunkweb_csrf_token_8000=15573489094520950050, time=15823899
```

**Comment by jitlogic** [comment]
Zorka already has (kind of) integration with traditional logging systems. It's called trappers - it writes data to local files, zabbix or syslog. Potential drawback of current implementation is that it requires coding some BSH script for each method that has to be implemented as it is spy feature rather than tracer. There is auditing config script that standardizes auditing instrumentations plus there are some already configured instrumentations for CAS, JBoss, Tomcat etc.

When implementing alternative method via tracer one needs to remember that tracer can generate huge amounts of data and just few agents might easily overflow any log aggregator. Some filtering has to be implemented in order to limit amount of data generated (Zabbix module has such filtering, ZICO on the other hand has very good compression ratio for collected data).

**Comment by ltmon** [comment]
Thanks, I'll spend some time scripting the trapper feature and see if that can achieve what I'm after -- I eventually want request tracing data similar to that found in Intrascope or Websphere's Request Metrics. Preferably with a global request ID so the entire flow of a request via the spied methods can be seen. If the trapper feature with some scripting can achieve this then it's probably better than the path I'm working down.

Splunk (what I know well) works pretty smoothly in the 10s or 100s of GB/day, and I've used it with Websphere RM at 50GB/day, so with careful filtering this should be achievable.

I'll re-comment and close after looking deeper at trapper. Or just close if this is the best path in your opinion.

**Comment by jitlogic** [comment]
Trapper feature is much simpler than that, unfortunately. But it's already implemented for both HTTP, SQL and EJB requests - you just need to turn it on. Regarding binding between tracer and logs (global ID of some sort), it should be fairly easy to implement at BSH level, so I'm now thinking about adding it as a standard. Please note that not all requests are collected by ZICO collector. By default only 'problematic' ones (errors and requests exceeding predefined execution time) - this also can be changed using tracer.min.trace.time option (or similar ones). 

Regarding Intrascope, I'm not aware what exactly did they implement as I'm trying not to look at their solutions (in order to not be accused of copying their designs). So if you want some features you like but zorka is missing it, do not hesitate to submit them here - sooner or later these will be done :)

**Comment by rlewczuk** [comment]
If there are no additional requests regarding trapper / tracing, I'm closing this issue. Please reopen of you thing there is still something to do.
